### PR TITLE
Add Rocket Rides iOS App component

### PR DESCRIPTION
**Pull request by joeydong-stripe**
This adds the Rocket Rides iOS demo app to the repository.

r? @romain-stripe

### CODE REVIEW

**Comment by arjun-ram** [comment]
Does this mean we can integrate rocketrides functionality into our iOS apps? Thanks!

**Comment by joeydong-stripe** [comment]
Hi @arjun-ram,

I'm not sure I understand your question. What functionality do you have in mind?

The Rocket Rides iOS app is basically an app that connects to the backend that's already in this repository. Check out this README for more info: https://github.com/joeydong-stripe/stripe-connect-rocketrides/blob/d2641f925615f52598be84f1c1896796a3e63467/ios/README.md

**Comment by arjun-ram** [comment]
We use Stripe connect for our service. We have two apps one for our customers https://itunes.apple.com/us/app/sixlegs-dog-walkers-when-you/id1095753505?ls=1&mt=8 and one for our service providers. Was hoping that in the service provider app we can use the iOS component and do what RocketRides does for contractors. Ability to do instapay etc.

**Comment by joeydong-stripe** [comment]
Ah okay. Thanks for the context. This particular example app is focused on the customer facing side. You can still build a service provider app by using the Connect Express pages in a mobile web view.  Please email support@stripe.com and they'll help you get started with that.

**Comment by arjun-ram** [comment]
Was hoping for a native library. Any plans?

**Comment by joeydong-stripe** [comment]
Thanks for the suggestion. We'll take a look :)

**Comment by romain-stripe** [comment]
Thanks a lot, Joey! This is awesome. I'm gonna go ahead and merge your PR, then iterate on the main README and the code a bit. Thanks again! 👌

**Pull request merged**
